=== scenari/cid/discoverCid/manifest/cid-core.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	targetNamespace="http://www.cid-protocol/schema/v1/core"
	xmlns:cid="http://www.cid-protocol/schema/v1/core">	
	<xs:import schemaLocation="http://www.w3.org/2001/xml.xsd" namespace="http://www.w3.org/XML/1998/namespace"/>

	<xs:element name="manifest">
		<xs:complexType>
			<xs:sequence>
				<!-- Human oriented documentation -->
				<xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="cid:localized-element"/>
				<xs:element name="doc" minOccurs="0" maxOccurs="unbounded" type="cid:localized-element"/>
				
				<!-- list of process -->
				<xs:element name="process" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<!-- Human oriented process documentation -->					
							<xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="cid:localized-element"/>
							<xs:element name="doc" minOccurs="0" maxOccurs="unbounded" type="cid:localized-element"/>
							<!-- Meta and restriction declarationwebAsyncUpload -->
							<xs:element name="restriction" minOccurs="0" maxOccurs="unbounded" type="cid:restriction-element"/>
							<xs:element name="meta" minOccurs="0" maxOccurs="unbounded" type="cid:meta-element"/>
							<!-- Steps declaration -->
							<xs:choice maxOccurs="unbounded">
								<xs:element name="exchange" type="cid:asyncStep-element"/>
								<xs:element name="upload" type="cid:asyncStep-element"/>
								<xs:element name="interact" type="cid:regularStep-element"/>
							</xs:choice>
						</xs:sequence>
						
						<!-- Bind a this process to a specific transport -->
						<xs:attribute name="transports" type="xs:IDREFS"/>
						<!-- Computer oriented process description -->
						<xs:attribute name="is" type="cid:uri-list"/>
					</xs:complexType>
				</xs:element>
				
				<!-- List of defined transports -->
				<xs:element name="transports">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<!-- Web transport declaration -->
							<xs:element name="webTransport">
								<xs:complexType>
									<xs:all>
										<!-- First transport declaration step : supported authentication -->
										<xs:element name="authentications">
											<xs:complexType>
												<!-- An empty authentications element means "no authentication needed" --> 
												<xs:choice minOccurs="0" maxOccurs="unbounded">
													<xs:element name="noAuthentication"><xs:complexType/></xs:element>
													<xs:element name="basicHttp"><xs:complexType/></xs:element>
													<!-- Must be operated as a web interact -->
													<xs:element name="webAuthentication">
														<xs:complexType>
															<xs:attribute name="url" type="xs:anyURI"/>
														</xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
										
										<!-- List of step transport declaration -->
										<xs:element name="webExchange" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="request" type="cid:regularRequest" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="webInteract" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="request" type="cid:regularRequest" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="webUpload" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="request" type="cid:uploadRequest" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:all>
									
									<!--  Id needed to bind a process to a specific transport -->
									<xs:attribute name="id" type="xs:ID"/>
									<!--  True if the server use a cookies -->
									<xs:attribute name="needCookies" type="xs:boolean"/>
									<!--  
										Names of session properties. A session properties must be neutrally handled
										 (returned by the client if sent by the server 
									-->
									<xs:attribute name="sessionProperties" type="cid:propName-list"/>
								</xs:complexType>
							</xs:element>
							<xs:any namespace="##other"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<!-- *****************************************************************
								SIMPLE TYPE LIBRARY
	***************************************************************** -->
	
	<!-- List of uris (is attribute) -->
	<xs:simpleType name="uri-list">
		<xs:restriction>
			<xs:simpleType>
				<xs:list itemType="xs:anyURI"/>
			</xs:simpleType>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- List of properties name (sessionProperties attribute) -->
	<xs:simpleType name="propName-list">
		<xs:restriction>
			<xs:simpleType>
				<xs:list itemType="xs:NCName"/>
			</xs:simpleType>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- request method token definition (get or post) -->
	<xs:simpleType name="getPost-token">
		<xs:restriction base="xs:token">
			<xs:enumeration value="GET"/>
			<xs:enumeration value="POST;application/x-www-form-urlencoded"/>
			<xs:enumeration value="POST;multipart/form-data"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- request method token definition (get, put or post) -->
	<xs:simpleType name="getPutPost-token">
		<xs:restriction base="xs:token">
			<xs:enumeration value="GET"/>
			<xs:enumeration value="PUT"/>
			<xs:enumeration value="POST"/>
			<xs:enumeration value="POST;multipart/form-data"/>
		</xs:restriction>
	</xs:simpleType>
 
	<!-- list of properties storage method (header, querystring or post) -->
	<xs:simpleType name="postProp-list">
		<xs:restriction>
			<xs:simpleType>
				<xs:list>
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:enumeration value="header"/>
							<xs:enumeration value="queryString"/>
							<xs:enumeration value="post"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:list>
			</xs:simpleType>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>

	
	<!-- *****************************************************************
								COMPLEXE TYPE LIBRARY
	***************************************************************** -->
	
	<!-- localized informations (used to write human oriented doc) -->
	<xs:complexType name="localized-element" mixed="true">
		<xs:attribute ref="xml:lang"/>
	</xs:complexType>
    
    <!-- restriction element -->
	<xs:complexType name="restriction-element">
		<xs:sequence>
			<xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="cid:localized-element"/>
			<xs:element name="doc" minOccurs="0" maxOccurs="unbounded" type="cid:localized-element"/>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:NCName"/>
		<xs:attribute name="is" type="cid:uri-list"/>
		<xs:attribute name="value" use="required" type="xs:string"/>
	</xs:complexType>
	
	<!-- meta element -->
	<xs:complexType name="meta-element">
		<xs:sequence>
			<xs:element name="label" minOccurs="0" maxOccurs="unbounded" type="cid:localized-element"/>
			<xs:element name="doc" minOccurs="0" maxOccurs="unbounded" type="cid:localized-element"/>
			<xs:element name="value" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType mixed="true"/>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:ID"/>
		<xs:attribute name="cardinality">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="1"/>
					<xs:enumeration value="?"/>
					<xs:enumeration value="+"/>
					<xs:enumeration value="*"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="is" type="cid:uri-list"/>
	</xs:complexType>
	
	<!-- common step attribute -->
	<xs:complexType name="step-commons">
		<xs:attribute name="url" use="required" type="xs:anyURI"/>
		<xs:attribute name="needMetas" type="xs:IDREFS"/>
		<xs:attribute name="useMetas" type="xs:IDREFS"/>
		<xs:attribute name="returnMetas" type="xs:IDREFS"/>
	</xs:complexType>
	
	<!-- Step element (used by interact and asyncStep) -->
	<xs:complexType name="regularStep-element">
		<xs:complexContent>
			<xs:extension base="cid:step-commons">
				<xs:attribute name="is" type="cid:uri-list"/>
				<xs:attribute name="required" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- Step element (used by upload and exchange) -->
	<xs:complexType name="asyncStep-element">
		<xs:complexContent>
			<xs:extension base="cid:regularStep-element">
				<xs:all>
					<xs:element name="systemWait" minOccurs="0">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="cid:step-commons">
									<xs:attribute name="waitProperties" type="cid:propName-list"/>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="userWait" minOccurs="0" type="cid:step-commons"/>
				</xs:all>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Definition of a regular request (exchange/interact) -->
	<xs:complexType name="regularRequest">
		<xs:attribute name="method" use="required" type="cid:getPost-token"/>
		<xs:attribute name="properties" use="required" type="cid:postProp-list"/>            
	</xs:complexType>
  
	<!-- Definition of a request which contains -->
	<xs:complexType name="uploadRequest">
		<xs:attribute name="method" use="required" type="cid:getPutPost-token"/>
		<xs:attribute name="properties" use="required" type="cid:postProp-list"/>            
	</xs:complexType>
	
	<!-- Definition of a transport property -->
	<xs:complexType name="property">
		<xs:attribute name="key" use="required" type="xs:ID"/>
		<xs:attribute name="value" use="required" type="xs:NCName"/>
	</xs:complexType>
	
	
	
	
	
	
	
</xs:schema>

=== scenari/cid/discoverCid/examples/4-scormUpload.xml
<?xml version="1.0" encoding="UTF-8"?>
<cid:manifest xmlns:cid="http://www.cid-protocol/schema/v1/core" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cid-protocol/schema/v1/core ../manifest/cid-core.xsd ">
	<!-- 
		This manifest declares two transports : the first without cookies, the 
		second with. Two processes are also defined. They are respectively binded 
		to the two different webtransports.
	-->
    
	<!-- 
		This process is binded to standard Transport. It uses a session property to
		enable statefull servers.
	-->
	<cid:process transports="standardTransport" is="http://schema.org/SendAction">
		<cid:label xml:lang="en">SCORM deployment</cid:label>

		<!-- 
			A restriction is similar to a meta with the difference that the 
			restriction is implicit in the process. The value is unique and set only
			once in the manifest and never sent by the client.
		-->
		<cid:restriction name="Zip-file-names-encoding" value="UTF-8">
			<cid:label xml:lang="en">Encoding of the files-name</cid:label>
		</cid:restriction>
        
		<!-- Definition of custom mimeType -->
		<cid:meta name="Content-type" is="http://purl.org/dc/elements/1.1/type">
			<cid:value>application/xx-scorm;v1.2</cid:value>
			<cid:value>application/xx-scorm;v2004</cid:value>
		</cid:meta>

		<cid:upload url="http://example.com/upload?response=noCookies" needMetas="Content-type" required="true"/>
		<cid:interact url="http://example.com/interact?response=noCookies" required="true"/>
	</cid:process>
    
	<!-- 
			This process is binded to the second transport. It needs a client which 
			supports cookies 
		-->
	<cid:process transports="transportWithCookies" is="http://schema.org/SendAction">
		<cid:restriction name="Zip-file-names-encoding" value="UTF-8"/>
		<cid:upload url="http://example.com/upload?response=withCookies" needMetas="Content-type" required="true"/>
		<cid:interact url="http://example.com/interact?response=withCookies" required="true"/>
	</cid:process>

	<cid:transports>
		<cid:webTransport id="standardTransport">
			<cid:authentications>
				<cid:basicHttp/>
			</cid:authentications>
			<cid:webInteract>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST;application/x-www-form-urlencoded" properties="queryString header post"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
			</cid:webInteract>
            
            <cid:webUpload>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST" properties="queryString header"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
            </cid:webUpload>
		</cid:webTransport>
        
		<cid:webTransport id="transportWithCookies" needCookies="true">
			<cid:authentications>
				<cid:basicHttp/>
			</cid:authentications>
			<cid:webInteract>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST;application/x-www-form-urlencoded" properties="queryString header post"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
			</cid:webInteract>
            
            <cid:webUpload>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST" properties="queryString header"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
            </cid:webUpload>
		</cid:webTransport>
	</cid:transports>
</cid:manifest>

=== scenari/cid/discoverCid/examples/1-simpleUpload.xml
<?xml version="1.0" encoding="UTF-8"?>
<cid:manifest xmlns:cid="http://www.cid-protocol/schema/v1/core" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cid-protocol/schema/v1/core ../manifest/cid-core.xsd ">
	<cid:process>
		<cid:label xml:lang="fr">Téléversement de fichier</cid:label>
		<cid:label xml:lang="en">File upload</cid:label>
		<cid:meta name="File-name" cardinality="?" is="http://purl.org/dc/elements/1.1/title">
			<cid:label xml:lang="fr">Nom du fichier</cid:label>
			<cid:label xml:lang="en">File name</cid:label>
			<cid:doc xml:lang="en">
                The file-name will be used in the public url of the file
                Example: http://.../1d57fe87zr45sdz796m/monImage.png
			</cid:doc>
		</cid:meta>
		<cid:meta name="Public-url" is="http://schema.org/URL"/>
		<!-- 
			The following fragment is the main part of the process declaration. It 
			describes each step of the process.
			Each step declares the (previously-documented) used (optional), needed 
			or returned metadatas. This process contains only one step: the upload 
			step which is required to complete the file deposit and which is 
			composed by only one request (attribute step="unique"). This step 
			accepts the File-name metadata and returns the Public-url of the 
			uploaded file.
		-->
		<cid:upload url="http://example.com/upload.php" useMetas="File-name" returnMetas="Public-url" required="true"/>
	</cid:process>
	<!--
		The second part of the manifest is dedicated to the enabled authentication
		methods.
	-->
	
	
	<!-- 
		The last part of the manifest is dedicated to the transport declaration.
		In this example, the transport is a single HTTP request. The properties 
		attribute defines how the metadata should be sent.
		The returned properties must be inserted in a single JSON object in the 
		body of the HTTP response.
	-->
	<cid:transports>
		<cid:webTransport>
			<cid:authentications>
				<cid:basicHttp/>
			</cid:authentications>
			<cid:webUpload>
				<cid:request  method="PUT"  properties="header queryString"/>
				<cid:request  method="POST"  properties="header queryString"/>
				<cid:request  method="POST;multipart/form-data"  properties="header queryString post"/>
			</cid:webUpload>
		</cid:webTransport>
	</cid:transports>
</cid:manifest>

=== scenari/cid/discoverCid/examples/3-UploadWithUserInteraction.xml
<?xml version="1.0" encoding="UTF-8"?>
<cid:manifest xmlns:cid="http://www.cid-protocol/schema/v1/core" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cid-protocol/schema/v1/core ../manifest/cid-core.xsd ">
	<cid:process is="http://schema.org/SendAction">
		<cid:label xml:lang="fr">DÃ©pot de d'archives de ressources</cid:label>
		<cid:meta name="Folder-path">
			<cid:label xml:lang="en">Storage folder</cid:label>
			<cid:doc xml:lang="en">
                Path to the folder where the archive is unarchived.
			</cid:doc>
		</cid:meta>
		<!--
			The content-type metadata describes the type of the archive (and not of
			its content). In this description, the server furnishes three possible 
			values. The client must select a value between them.
		-->
		<cid:meta name="Content-type" is="http://purl.org/dc/elements/1.1/type">
			<cid:label xml:lang="en">Available archived format</cid:label>
			<cid:value>application/zip</cid:value>
			<cid:value>application/jar</cid:value>
			<cid:value>application/x-tar</cid:value>
		</cid:meta>
		<!--
			The names of the files compressed in a zip archive could be encoded
			following several schemes. In order to correctly decode it, this server 
			request the encoding scheme as a metadata.
		-->
		<cid:meta name="Zip-file-names-encoding">
			<cid:label xml:lang="fr">File name encoding of the archive</cid:label>
			<cid:doc xml:lang="fr">This metadata should be sent if the Content-type is "application/zip".</cid:doc>
			<cid:value>UTF-8</cid:value>
			<cid:value>ISO-8859-1</cid:value>
			<cid:value>CP437</cid:value>
		</cid:meta>
		<!--
			This process is composed of two steps :
			
			1. An optional interaction step (which could use the Folder-path 
			metadata). This interaction allows the user to define the path where 
			the file will be unarchived. In this example, the Folder-path could be 
			sent by the client in the request. The server could then build a 
			dedicated GUI where this path is already selected. The server returns 
			the overloaded Folder-path value in the "cid-interaction-ended" event.

			2. A required upload step, which needs the folder-path and the
			content-type metadata and which could use the Zip-file-names-encoding
			metadata.
		-->
		<cid:interact url="http://..." useMetas="Folder-path" returnMetas="Folder-path" required="false"/>
		<cid:upload url="http://..." needMetas="Zip-file-names-encoding Content-type Folder-path" required="true"/>
	</cid:process>
	<!-- 
		The web transport specified by this server includes a session property.
		This property could be returned whith the metadata at each step of the 
		process. When this property is returned, the client must send it back in the
		next step of the process. This feature enables statefull servers.
	-->
	<cid:transports>
		<cid:webTransport sessionProperties="session-ID">
			<cid:authentications>
				<cid:basicHttp/>
				<cid:webAuthentication/>
			</cid:authentications>
			<cid:webInteract>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST;application/x-www-form-urlencoded" properties="queryString header post"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
			</cid:webInteract>
			<cid:webUpload>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST" properties="queryString header"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
			</cid:webUpload>
		</cid:webTransport>
	</cid:transports>
</cid:manifest>

=== scenari/cid/discoverCid/examples/2-retrieveMetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<cid:manifest xmlns:cid="http://www.cid-protocol/schema/v1/core" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cid-protocol/schema/v1/core ../manifest/cid-core.xsd ">
	<cid:process is="http://schema.org/FindAction http://schema.org/CheckAction">
		<cid:label xml:lang="en">Public URL retrieving</cid:label>
		<cid:doc xml:lang="en">Browse your online contents to retrieve a public URL.</cid:doc>
		<cid:meta name="Public-url"  is="http://schema.org/url"/>
		<!-- The process is composed by a single interaction step. -->
		<cid:interact url="http://.." returnMetas="Public-url" required="true"/>
	</cid:process>
	<!-- 
		The web interaction begins with a single HTTP request and ends with a 
		custom javascript event named "cid-interaction-ended". The client must 
		instantiate a web frame and fill it with the result of the first request.
		It gets the returned metadata in the body of the custom event. In this 
		example, the server does not furnish any authentication scheme. It could 
		handle a web authentication in the frame.
	-->
	<cid:transports>
		<cid:webTransport>
			<cid:authentications>
				<cid:noAuthentication/>
			</cid:authentications>
			<cid:webInteract>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST;application/x-www-form-urlencoded" properties="queryString header post"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
			</cid:webInteract>
		</cid:webTransport>
	</cid:transports>
</cid:manifest>

=== scenari/cid/discoverCid/examples/5-videoUpload.xml
<?xml version="1.0" encoding="UTF-8"?>
<cid:manifest xmlns:cid="http://www.cid-protocol/schema/v1/core" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cid-protocol/schema/v1/core ../manifest/cid-core.xsd ">
	<cid:process is="http://schema.org/SendAction">
		<cid:label xml:lang="en">DAM</cid:label>
		<cid:meta name="Content-type" is="http://purl.org/dc/elements/1.1/type">
			<cid:value>image/png</cid:value>
			<cid:value>video/mpeg4</cid:value>
		</cid:meta>

		<cid:meta name="Public-url"  is="http://schema.org/url"/>
		<!-- 
			Meta could have cardinality (1, ?, * or +). Default cardinality is 1.
		-->
		<cid:meta name="dc-title" cardinality="?" is="http://purl.org/dc/elements/1.1/title"/>
		<cid:meta name="dc-creator" cardinality="?" is="http://purl.org/dc/elements/1.1/creator"/>
		<cid:meta name="dc-modified" cardinality="?" is="http://purl.org/dc/terms/modified"/>
		<cid:meta name="tags" cardinality="*" is="http://schema.org/keywords"/>

		<!-- 
			An exchange step represents a default HTTP request.

			In this process, the content to upload could be really large. This first 
			optional step allows a client to check the authentication and 
			authorization of a user before sending the content.
		-->
		<cid:exchange url="http://example.com/checkAuthorization" is="http://schema.org/AuthorizeAction" required="false"/>
		<cid:interact url="http://example.com/interact-pre-delivery" useMetas="dc-title dc-creator dc-modified" returnMetas="dc-title dc-creator dc-modified tags" required="true"/>
		<!-- 
			Async upload.
			Ã€ documenter
		-->
		<cid:upload url="http://example.com/upload?step=start" needMetas="dc-title dc-creator dc-modified tags" required="true">
			<cid:systemWait url="http://example.com/wait?method=system" returnMetas="Public-url"/>
			<cid:userWait url="http://example.com/wait?method=user" returnMetas="Public-url"/>
		</cid:upload>
				
	</cid:process>

	<cid:transports>
		<cid:webTransport sessionProperties="session-ID">
			<cid:authentications>
				<cid:basicHttp/>
				<cid:webAuthentication/>
			</cid:authentications>

			<cid:webExchange>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST;application/x-www-form-urlencoded" properties="queryString header post"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
			</cid:webExchange>
           
			<cid:webInteract>
				<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST;application/x-www-form-urlencoded" properties="queryString header post"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
			</cid:webInteract>
     
			<cid:webUpload>
     			<cid:request method="GET" properties="header queryString"/>
				<cid:request method="POST" properties="queryString header"/>
				<cid:request method="POST;multipart/form-data" properties="header queryString post"/>
			</cid:webUpload>
		</cid:webTransport>
	</cid:transports>
</cid:manifest>
